### ISSUE TITLE
Consider Allowing JMS Autoconfig to use Java Credentials

### ISSUE THREAD

**Issue by Mrc0113** [SolaceProducts/solace-spring-boot#3]
Consider expanding the Spring Boot JMS autoconfig to use the `solace.java` credential properties if `solace.jms` ones are not specified. This would allow for an app that uses Spring Boot JMS in conjunction with the Spring Cloud Stream Binder or Spring  Boot JCSMP to only have to specify credentials once rather than twice like shown below: 

```
solace:
  java:
    host: ${host:tcp://localhost:55555}
    msgVpn: ${msgVpn:default}
    clientUsername: ${clientUsername:default}
    clientPassword: ${clientPassword:default}
  jms:
    host: ${host:tcp://localhost:55555}
    msgVpn: ${msgVpn:default}
    clientUsername: ${clientUsername:default}
    clientPassword: ${clientPassword:default}
```
